version: "2.1"
services:
  jackett:
    image: linuxserver/jackett:arm64v8-latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
      - AUTO_UPDATE=true 
      - RUN_OPTS=<run options here> #optional
    volumes:
      - config:/config
      - <path to blackhole>:/downloads
    ports:
      - 9117:9117
    restart: always